//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee
    {
        public long ID { get; set; }
        public string Family_Name { get; set; }
        public string First_Name { get; set; }
        public string Date_Hired { get; set; }
        public Nullable<decimal> DailyWage { get; set; }
        public string Date_Resigned { get; set; }
        public string EmployeePhoto { get; set; }
        public bool IsDeleted { get; set; }
        public string CreateID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
